### ISSUE TITLE
Packet ID mismatch

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#10]
Whenever a command sequence includes deactivate reactivate, psyllid crashes because of an packet ID mismatch.

This is what psyllid is doing after activate (no run started):
[psyllid_activity_after_activate.txt](https://github.com/project8/psyllid/files/526733/psyllid_activity_after_activate.txt)

This is the debugging information after deactivate - activate:
[deactivate-activate.txt](https://github.com/project8/psyllid/files/526737/deactivate-activate.txt)

This is the output after finish_configure - finish_configure:
[_finish_configure-_finish_configure.txt](https://github.com/project8/psyllid/files/526745/_finish_configure-_finish_configure.txt)

And finally starting and stopping a run which has this command sequence:
[start-run_end-run_in_dragonfly.txt](https://github.com/project8/psyllid/files/526746/start-run_end-run_in_dragonfly.txt)

leads to:
[start_stop_deactivate_activate.txt](https://github.com/project8/psyllid/files/526747/start_stop_deactivate_activate.txt)

Egg files were written during the run.

**Comment by nsoblath** [comment]
This is no longer relevant after significant code changes.  Please create a new issue if similar problems still show up.
