### ISSUE TITLE
exit due to handled error results in a success code

### ISSUE THREAD

**Issue by laroque** [project8/psyllid#111]
# What happened
I ran a psyllid instance which duplicated an existing one, there was an error through AMQP because the queue was unavailable. The error was processed by signal_handler with the result that the psyllid executable exited returning 0.

# What I expected
The psyllid application should have returned a non-zero code, indicating an error.

# Notes
I'd describe the current behavior as "incorrect" but it isn't currently causing me any problems. The only symptom is that containers sometimes appear to have "Completed" rather than "Error" status; this may be a problem when running cluster jobs, since the job system expects to use those return codes to determine if the job failed.

**Comment by nsoblath** [comment]
Fixed in v1.10.2
