### ISSUE TITLE
psyllid executable not in container $PATH

### ISSUE THREAD

**Issue by wcpettus** [project8/psyllid#113]
In the OS-specific psyllid debian containers, the psyllid executable is installed to a directory not in $PATH, and consequently psyllid cannot be trivially located.  Preferably the container will spin up and not require a setup file to locate this executable.

Either the build install path should be changed to a common install point like /usr/local/bin, or $PATH should be extended to include the build install point.

Also verify that the Dockerfile in the repo defaults to have psyllid build in a useful location.

**Comment by nsoblath** [comment]
Fixed in v1.12.3
