### ISSUE TITLE
with fmt: midge error: unable to prepare egg file

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#14]
[unable_to_prepare_egg_file.txt](https://github.com/project8/psyllid/files/540164/unable_to_prepare_egg_file.txt)

**Comment by nsoblath** [comment]
This looks like a problem that was caused by a bug that's already been solved.  @cclaessens, please test this again and post whether or not the problem still exists.

**Comment by cclaessens** [comment]
problem does not exist anymore
