### ISSUE TITLE
psyllid appearantly doesnt record first second of a run

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#15]
since daq worker was removed

**Comment by cclaessens** [comment]
Only the first run which is started results in a very small egg file. The subsequent runs have a more promising size. When one waits a bit (30sec) after activate and daq-status calls and then starts a run the size of the first file seems ok (size comparable to order of magnitude of subsequent runs). 

The sizes vary strongly from run to run but I suspect that might be linked to the ID sequence issue.

ls -lh output
a-files belong to runs of 1000ms and b-files to 2000ms runs.

-rw-rw-r-- 1 cclaesse cclaesse 124K Nov  2 15:38 a0.egg
-rw-rw-r-- 1 cclaesse cclaesse  13M Nov  2 15:38 a1.egg
-rw-rw-r-- 1 cclaesse cclaesse 2.3M Nov  2 15:38 a2.egg
-rw-rw-r-- 1 cclaesse cclaesse  13M Nov  2 15:39 a3.egg
-rw-rw-r-- 1 cclaesse cclaesse 9.4M Nov  2 15:39 a4.egg
-rw-rw-r-- 1 cclaesse cclaesse 4.0M Nov  2 15:39 a5.egg
-rw-rw-r-- 1 cclaesse cclaesse  21M Nov  2 15:40 b0.egg
-rw-rw-r-- 1 cclaesse cclaesse  22M Nov  2 15:40 b1.egg

**Comment by nsoblath** [comment]
This was fixed by reducing delays after the run timer started but before the run itself started.  It's fixed at some point before fe922235b6051139bb4cf9813b54db65c78821e5.
