### ISSUE TITLE
Sequential packet recording

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#16]
Currently only packets with matching f and t ID are processed and missing packets result are skipped and a new event is started.

Running psyllid with the fpa receiver resulted in a lot of warnings from the roach_receiver about Improper packet sizes and a small egg file.
After adding a warning which is printed when the packet size is as expected it seems that in a 100ms run 1 out of 2 packets have the wrong size.
To produce the following output I also added a debug line ("acquisition break") which is written when the streaming writer doesn't get the packet it expects.
Acquisitions are always only 1 record long.

[fpa_run_output.txt](https://github.com/project8/psyllid/files/586169/fpa_run_output.txt)

In a run with the socket receiver the packet sizes seem to always be as expected and acquisitions have more records. Breaks occur regularly too.

[socket_run_output.txt](https://github.com/project8/psyllid/files/586176/socket_run_output.txt)

**Comment by nsoblath** [comment]
I'm not able to replicate this problem.  Are you sure you're using the latest commit?  I had something like this happening yesterday, but I fixed the bug in that case.  I'm writing this as of commti 3fce23f.

**Comment by nsoblath** [comment]
Nevermind my last comment.  I hadn't been performing a run.  I do replicate the problem.

**Comment by nsoblath** [comment]
This was fixed in commit 8da44ce643886435d550c2a13db9468bf80b96c0
