### ISSUE TITLE
egg files cannot be processed with katydid

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#18]
[katydidoutput.txt](https://github.com/project8/psyllid/files/586206/katydidoutput.txt)

When I created fake data and wanted to process it with katydid I had some data type issues too. But the error then clearly stated that katydid wanted complex 32 float. So I guess this is now at an earlier level.

Katydid starts of very promising:
22:41:09 [DEBUG] rch3/M3Stream.cc(173): 	Number of acquisitions found: 102; Number of records found: 1867

It also gets the header and the only warnings appearing are:
22:41:09 [ WARN] gleChannelDAC.cc(229): level <129> = 0

and later:
22:41:09 [ WARN] KTForwardFFTW.cc(158): Unable to read FFTW wisdom from file <wisdom_complexfft.fftw3>

Katydid also gets the slice headers and has all the information about the slice but then:
22:41:09 [ INFO] KTForwardFFTW.cc(367): binwidth 1e-08
22:41:09 [ INFO] KTForwardFFTW.cc(377): iComponent0
22:41:09 [ERROR] KTForwardFFTW.cc(378): Incorrect time series type: time series did not cast to KTTimeSeriesFFTW.
22:41:09 [ERROR] cessor/KTSlot.hh(322): Something went wrong while analyzing data with type <N7Katydid16KTTimeSeriesDataE>

The lines in ForwardFFTW producing this are:
        {
            const KTTimeSeriesFFTW* nextInput = dynamic_cast< const KTTimeSeriesFFTW* >(tsData.GetTimeSeries(iComponent));
            if (nextInput == NULL)
            {
                KTERROR(fftwlog, "Incorrect time series type: time series did not cast to KTTimeSeriesFFTW.");
                return false;
}

**Comment by nsoblath** [comment]
- [ ] Fix setting of digitizer parameters (in particular DAQ gain) in streaming_writer and egg_writer
- [x] Tell Katydid that it's dealing with FFTW time series
- [ ] Figure out how to make Katydid recognize FFTW time series by itself
- [ ] Fix how FFTW time series are handled at the RawTimeSeries level -- this is the underlying cause of weird memory errors that inconsistently appear

**Comment by nsoblath** [comment]
Done at commit fcbd65e56fd592c339ce7c255037c47cc5ae0b4e
