### ISSUE TITLE
Psyllid log oddities

### ISSUE THREAD

**Issue by wcpettus** [project8/psyllid#30]
Two enhancements for the psyllid stdout/stderr logs:
- add date (in addition to time) stamp to log to make it easier to browse through old logs
- only last 16 characters of file name are kept in log, resulting in logs like:
```
17:43:58 [ PROG] ol/run_server.cc(50): Creating server objects
17:43:58 [ PROG] tterfly_house.cc(65): Prepared file <0>; default filename is <psyllid_out_0.egg>
```

As a further enhancement, the log files are very sparse - they only appear to have startup and crash information.

**Comment by nsoblath** [comment]
I moved this to https://github.com/project8/scarab/issues/17 since the logger is part of scarab.
