### ISSUE TITLE
psyllid cannot reactivate

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#38]
While it is possible to "manually" deactivate psyllid and activate it again, asking it to reactivate results in psyllid being caught in deactivating.

04:53:47 [DEBUG] (tid 140288597190400) ource/service.cc(238): Determined the RKS to be <reactivate-daq>; size = 1                                                                              [44/1935]
04:53:47 [DEBUG] (tid 140288597190400) pp/source/hub.cc(160): Cmd request received
04:53:47 [DEBUG] (tid 140288597190400) pp/source/hub.cc(304): Authenticating with key <00000000-0000-0000-0000-000000000000>
04:53:47 [DEBUG] (tid 140288597190400) l/daq_control.cc(280): Deactivating DAQ
04:53:47 [DEBUG] (tid 140288597190400) l/daq_control.cc(295): Canceling DAQ worker from DAQ control
04:53:47 [DEBUG] (tid 140288597190400) /core/diptera.cc(342): Canceling nodes: producers
04:53:47 [DEBUG] (tid 140288597190400) /core/diptera.cc(347): Canceling ch1_prf
04:53:47 [DEBUG] (tid 140288597190400) ary/core/node.cc(107): node::do_cancellation for <ch1_prf>
04:53:47 [DEBUG] (tid 140288597190400) ary/core/node.cc(110): Canceling stream <out_0>
04:53:47 [DEBUG] (tid 140288597190400) ty/cancelable.cc(28): cancelable::do_cancellation
04:53:47 [ERROR] (tid 140288563619584) _receiver_fpa.cc(246): Exiting due to stream error
04:53:47 [ INFO] (tid 140288563619584) _receiver_fpa.cc(269): Packet receiver is exiting
04:53:47 [DEBUG] (tid 140288563619584) _receiver_fpa.cc(272): Stopping output streams
04:53:47 [ INFO] (tid 140288554174208) oach_receiver.cc(138): TF ROACH receiver is exiting
04:53:47 [DEBUG] (tid 140288554174208) oach_receiver.cc(141): Stopping output streams
04:53:47 [DEBUG] (tid 140288554174208) oach_receiver.cc(145): Exiting output streams
04:53:47 [DEBUG] (tid 140288545781504) ggered_writer.cc(149): Triggered writer received stop command on the time stream while already stopped; no action taken
04:53:47 [DEBUG] (tid 140288572012288) _mask_trigger.cc(482): FMT is stopping at stream index 2
04:53:47 [DEBUG] (tid 140288572012288) _mask_trigger.cc(489): FMT is exiting at stream index 3
04:53:47 [DEBUG] (tid 140288572012288) _mask_trigger.cc(500): FMT has exited the apply-threshold while loop; possible reasons: is_canceled() = 0; f_break_exe_func.load() = 0
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(156): Event builder is stopping at stream index 2
04:53:47 [ INFO] (tid 140288572012288) _mask_trigger.cc(508): FMT is exiting
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(158): Flushing pretrigger buffer as untriggered
04:53:47 [DEBUG] (tid 140288572012288) _mask_trigger.cc(511): Stopping output stream
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(181): Event builder is exiting at stream index 3
04:53:47 [DEBUG] (tid 140288545781504) ggered_writer.cc(142): Triggered writer is exiting due to time-stream command; no run in progress
04:53:47 [DEBUG] (tid 140288572012288) _mask_trigger.cc(514): Exiting output stream
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(183): Flushing pretrigger buffer as untriggered
04:53:47 [ INFO] (tid 140288572012288) _mask_trigger.cc(172): FMT has exited
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(203): Stopping output stream
04:53:47 [DEBUG] (tid 140288588797696) event_builder.cc(206): Exiting output stream
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(357): Canceling nodes: transformers
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(362): Canceling ch1_eb
04:53:48 [DEBUG] (tid 140288597190400) ary/core/node.cc(107): node::do_cancellation for <ch1_eb>
04:53:48 [DEBUG] (tid 140288597190400) ary/core/node.cc(110): Canceling stream <out_0>
04:53:48 [DEBUG] (tid 140288597190400) ty/cancelable.cc(28): cancelable::do_cancellation
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(362): Canceling ch1_fmt
04:53:48 [DEBUG] (tid 140288597190400) ary/core/node.cc(107): node::do_cancellation for <ch1_fmt>
04:53:48 [DEBUG] (tid 140288597190400) ary/core/node.cc(110): Canceling stream <out_0>
04:53:48 [DEBUG] (tid 140288597190400) ty/cancelable.cc(28): cancelable::do_cancellation
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(362): Canceling ch1_tfrr
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(367): Canceling nodes: consumers
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(372): Canceling ch1_trw
04:53:48 [DEBUG] (tid 140288597190400) ary/core/node.cc(107): node::do_cancellation for <ch1_trw>
04:53:48 [DEBUG] (tid 140288597190400) /core/diptera.cc(377): Canceling nodes: bystanders
04:53:48 [DEBUG] (tid 140288597190400) l/daq_control.cc(252): Activating DAQ control
04:53:48 [ INFO] (tid 140288605583104) /core/diptera.cc(259): threads finished
04:53:48 [ INFO] (tid 140288605583104) l/daq_control.cc(149): DAQ control is shutting down after midge exited
04:53:48 [DEBUG] (tid 140288605583104) l/daq_control.cc(157): Midge has finished running
04:53:48 [DEBUG] (tid 140288597190400) pp/source/hub.cc(273): Sending reply message to <request_reply8d20cd72-a765-4110-8116-f49dc63b3c96>:
Return code: 200
Return message: Unable to reactivate DAQ control: DAQ control is not in the deactivated state

**Comment by cclaessens** [comment]
daq_control()::reactivate is just deactivate() followed by activate().
The reason why it works when I do it myself is that it takes longer and the status had time to change by the time I call activate(). Could be fixed by a 1 second sleep in daq_control()

**Comment by nsoblath** [comment]
I agree the 1-second pause should do the trick here.  It's conceivable that in rare cases it wouldn't be enough, but I'm going to go ahead and commit these changes without extensive testing.  If it crops up at all we can open a new issue.

Change applied in commit fb11b9c02b24c25cf65ec509c520868e84095da8.
