### ISSUE TITLE
non fatal midge error is not visible to the operator but undoes settings

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#40]
When a non fatal error occurs during a run, psyllid recovers and can start another run.
But after the recovery the frequency mask is lost and every packet gets written. In the current setup the operator may notice that a run resulted in too few files or that the next run results in too many.

Can we add something (in dragonfly) that will notice this happened and tell the operator, or should we maybe only have fatal errors?

**Comment by nsoblath** [comment]
This has been addressed in feature/moretalkative by adding posts to slack on the alerts channel for error messages.  I focused on `daq_control::execute()`.  Errors and caught exceptions in that function will post alerts.
