### ISSUE TITLE
psyllid does not seem to exit corrrectly during run when stopped (quit-psyllid command)

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#43]
03:17:50 [DEBUG] (tid 139770555123456) ol/run_server.cc(186): Canceling run server
	03:17:50 [DEBUG] (tid 139770555123456) ource/relayer.cc(97): Sending request to <status_message.notice.psyllid>
	03:17:50 [DEBUG] (tid 139770555123456) current_queue.hh(76): Attempting to push to queue
	03:17:50 [DEBUG] (tid 139770555123456) current_queue.hh(78): Pushing to concurrent queue; size: 3
	03:17:50 [DEBUG] (tid 139770555123456) uest_receiver.cc(198): Canceling request receiver
	03:17:50 [DEBUG] (tid 139770555123456) l/daq_control.cc(448): Canceling DAQ control
	03:17:50 [DEBUG] (tid 139770555123456) l/daq_control.cc(464): Canceling midge
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(342): Canceling nodes: producers
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(347): Canceling ch1_prf
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(107): node::do_cancellation for <ch1_prf>
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(110): Canceling stream <out_0>
	03:17:50 [DEBUG] (tid 139770555123456) ty/cancelable.cc(28): cancelable::do_cancellation
	03:17:50 [ INFO] (tid 139770030184192) _mask_trigger.cc(468): Data id <58111> [bin 2498] resulted in flag <1>data: 194;  mask1: 153.776
	03:17:50 [ INFO] (tid 139770021791488) event_builder.cc(157): Got another trigger: 7 need N triggers: 20
	03:17:50 [ INFO] (tid 139770030184192) _mask_trigger.cc(468): Data id <58113> [bin 3008] resulted in flag <1>data: 202;  mask1: 181.489
	03:17:50 [ INFO] (tid 139770021791488) event_builder.cc(157): Got another trigger: 8 need N triggers: 20
	03:17:50 [ERROR] (tid 139770038576896) _receiver_fpa.cc(246): Exiting due to stream error
	03:17:50 [ INFO] (tid 139770038576896) _receiver_fpa.cc(269): Packet receiver is exiting
	03:17:50 [DEBUG] (tid 139770038576896) _receiver_fpa.cc(272): Stopping output streams
	03:17:50 [DEBUG] (tid 139770013398784) l/daq_control.cc(403): Run stopper has been released
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(357): Canceling nodes: transformers
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(362): Canceling ch1_eb
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(107): node::do_cancellation for <ch1_eb>
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(110): Canceling stream <out_0>
	03:17:50 [DEBUG] (tid 139770555123456) ty/cancelable.cc(28): cancelable::do_cancellation
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(362): Canceling ch1_fmt
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(107): node::do_cancellation for <ch1_fmt>
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(110): Canceling stream <out_0>
	03:17:50 [DEBUG] (tid 139770555123456) ty/cancelable.cc(28): cancelable::do_cancellation
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(362): Canceling ch1_tfrr
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(367): Canceling nodes: consumers
	03:17:50 [ INFO] (tid 139770046969600) oach_receiver.cc(138): TF ROACH receiver is exiting
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(372): Canceling ch1_trw
	03:17:50 [DEBUG] (tid 139770046969600) oach_receiver.cc(141): Stopping output streams
	03:17:50 [DEBUG] (tid 139770555123456) ary/core/node.cc(107): node::do_cancellation for <ch1_trw>
	03:17:50 [DEBUG] (tid 139770555123456) /core/diptera.cc(377): Canceling nodes: bystanders
	03:17:50 [DEBUG] (tid 139770555123456) ource/relayer.cc(67): Canceling relayer
	03:17:50 [ INFO] (tid 139770013398784) l/daq_control.cc(408): Run has stopped
	03:17:50 [DEBUG] (tid 139770555123456) ource/service.cc(173): Service canceled
	03:17:50 [ INFO] (tid 139770555123456) uest_receiver.cc(131): No longer waiting for messages
	03:17:50 [ WARN] (tid 139770013398784) ource/relayer.cc(94): Relayer has been canceled; request not sent
	03:17:50 [ INFO] (tid 139770555123456) ource/service.cc(182): Stopping service on <channel_b_psyllid>
	03:17:50 [DEBUG] (tid 139770555123456) ource/service.cc(291): Stopping consuming messages (consumer amq.ctag-HPt0lNs77E9u_LfmTrkYJw)
	03:17:50 [ INFO] (tid 139770013398784) l/daq_control.cc(412): Run was cancelled
	03:17:50 [DEBUG] (tid 139770013398784) l/daq_control.cc(414): Finishing egg files
	03:17:50 [DEBUG] (tid 139770013398784) ty/cancelable.cc(28): cancelable::do_cancellation
	03:17:50 [ INFO] (tid 139770005006080) monarch3_wrap.cc(101): Monarch-on-deck manager is stopping
	03:17:51 [DEBUG] (tid 139770555123456) ource/service.cc(327): Deleting queue <channel_b_psyllid>
	03:17:51 [DEBUG] (tid 139770555123456) uest_receiver.cc(136): Request receiver is done
	03:17:51 [DEBUG] (tid 139770021791488) event_builder.cc(526): Stopping output stream
	03:17:51 [DEBUG] (tid 139770030184192) _mask_trigger.cc(533): FMT has exited the apply-threshold while loop; possible reasons: is_canceled() = 1; f_break_exe_func.load() = 0
	03:17:51 [ INFO] (tid 139770030184192) _mask_trigger.cc(541): FMT is exiting
	03:17:51 [DEBUG] (tid 139770030184192) _mask_trigger.cc(544): Stopping output stream
	03:17:51 [ INFO] (tid 139770030184192) _mask_trigger.cc(179): FMT has exited
	03:17:51 [ INFO] (tid 139770563516160) /core/diptera.cc(259): threads finished
	03:17:51 [ INFO] (tid 139770563516160) l/daq_control.cc(149): DAQ control is shutting down after midge exited
	03:17:51 [DEBUG] (tid 139770563516160) l/daq_control.cc(157): Midge has finished running
	03:17:51 [DEBUG] (tid 139770650625856) ol/run_server.cc(165): DAQ control thread has ended
	03:17:51 [DEBUG] (tid 139770650625856) ol/run_server.cc(168): Receiver thread has ended
	03:17:51 [DEBUG] (tid 139770650625856) ol/run_server.cc(173): Message relay thread has ended
	03:17:51 [ PROG] (tid 139770650625856) ol/run_server.cc(177): Threads stopped
	03:17:51 [ INFO] (tid 139770529945344) monarch3_wrap.cc(443): Monarch's execute-switch-loop for file </home/cclaessens/psyllid_test_data/trigger_test.egg> is stopping
	03:17:51 [ INFO] (tid 139770013398784) ch3/M3Monarch.cc(252): Finishing writing </home/cclaessens/psyllid_test_data/trigger_test_1.egg>
	03:17:51 [DEBUG] (tid 139770013398784) rch3/M3Stream.cc(672): Finalizing stream with 0 acquisitions and 0 records
	03:17:51 [DEBUG] (tid 139770013398784) monarch3_wrap.cc(196): On-deck file was written out to </home/cclaessens/psyllid_test_data/trigger_test_1.egg>; now removing the 
	file
	03:17:56 [ERROR] (tid 139770013398784) l/daq_control.cc(421): Unable to finish files: Streams did not all finish after 5 seconds
	03:17:56 [DEBUG] (tid 139770013398784) l/daq_control.cc(423): Canceling midge
	03:17:56 [DEBUG] (tid 139770650625856) tream_manager.cc(425): Clearing node bindings
	03:17:56 [ INFO] (tid 139770650625856) _receiver_fpa.cc(402): Turning off the FPA
	03:17:56 [ INFO] (tid 139770650625856) _receiver_fpa.cc(402): Turning off the FPA
	03:17:56 [DEBUG] (tid 139770650625856) _receiver_fpa.cc(412): Unmapping mmap ring
	03:17:56 [DEBUG] (tid 139770650625856) _receiver_fpa.cc(418): freeing f_rd
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class packet-receiver-fpa from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class packet-receiver-fpa from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class triggered-writer from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class triggered-writer from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class tf-roach-receiver from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class tf-roach-receiver from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class roach-freq-monitor from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class roach-freq-monitor from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class roach-time-monitor from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class roach-time-monitor from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-trig-flag from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-trig-flag from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-freq-data from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-freq-data from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-time-data from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class term-time-data from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class streaming-writer from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class streaming-writer from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class events-1ch-fpa from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class events-1ch from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class fmask-1ch-fpa from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class fmask-1ch from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class str-1ch-fpa from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class str-1ch from 0x1e286e0
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class packet-receiver-socket from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class packet-receiver-socket from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class frequency-mask-trigger from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class frequency-mask-trigger from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class event-builder from 0x1e27e90
	03:17:56 [DEBUG] (tid 139770650625856) ility/factory.hh(222): Removing factory for class event-builder from 0x1e27b00
	03:17:56 [DEBUG] (tid 139770650625856) monarch3_wrap.cc(604): Setting monarch stage to <3>
	03:17:56 [ INFO] (tid 139770650625856) ch3/M3Monarch.cc(252): Finishing writing </home/cclaessens/psyllid_test_data/trigger_test.egg>

**Comment by nsoblath** [comment]
Attempted fix pushed to branch feature/writerexit.  I've added a final attempt to close the streams being written to in each of the writers (streaming and triggered).  This should cover the case where the writer is canceled before it receives a stop or exit command on its input stream.

**Comment by cclaessens** [comment]
Fix works (with minor change in triggered writer). Line 401 in triggered writer.cc is reached and psyllid can close the stream and remove the factories:

	05:13:23 [ INFO] (tid 139650809255680) ol/run_server.cc(197): Shutting down the server                                                  
	05:13:23 [DEBUG] (tid 139650809255680) ol/run_server.cc(186): Canceling run server
	05:13:23 [DEBUG] (tid 139650809255680) ource/relayer.cc(97): Sending request to <status_message.notice.psyllid>
	05:13:23 [DEBUG] (tid 139650809255680) current_queue.hh(76): Attempting to push to queue
	05:13:23 [DEBUG] (tid 139650809255680) current_queue.hh(78): Pushing to concurrent queue; size: 3
	05:13:23 [DEBUG] (tid 139650809255680) uest_receiver.cc(198): Canceling request receiver
	05:13:23 [DEBUG] (tid 139650809255680) l/daq_control.cc(449): Canceling DAQ control
	05:13:23 [DEBUG] (tid 139650809255680) l/daq_control.cc(465): Canceling midge
	05:13:23 [DEBUG] (tid 139650809255680) /core/diptera.cc(342): Canceling nodes: producers
	05:13:23 [DEBUG] (tid 139650809255680) /core/diptera.cc(347): Canceling ch1_prf
	05:13:23 [DEBUG] (tid 139650809255680) ary/core/node.cc(107): node::do_cancellation for <ch1_prf>
	05:13:23 [ERROR] (tid 139650693973760) _receiver_fpa.cc(246): Exiting due to stream error
	05:13:23 [DEBUG] (tid 139650809255680) ary/core/node.cc(110): Canceling stream <out_0>
	05:13:23 [ INFO] (tid 139650693973760) _receiver_fpa.cc(269): Packet receiver is exiting
	05:13:23 [DEBUG] (tid 139650693973760) _receiver_fpa.cc(272): Stopping output streams
	05:13:23 [DEBUG] (tid 139650809255680) ty/cancelable.cc(28): cancelable::do_cancellation
	05:13:23 [DEBUG] (tid 139650115036928) l/daq_control.cc(404): Run stopper has been released
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(357): Canceling nodes: transformers
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(362): Canceling ch1_eb
	05:13:24 [DEBUG] (tid 139650809255680) ary/core/node.cc(107): node::do_cancellation for <ch1_eb>
	05:13:24 [DEBUG] (tid 139650809255680) ary/core/node.cc(110): Canceling stream <out_0>
	05:13:24 [DEBUG] (tid 139650809255680) ty/cancelable.cc(28): cancelable::do_cancellation
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(362): Canceling ch1_fmt
	05:13:24 [DEBUG] (tid 139650809255680) ary/core/node.cc(107): node::do_cancellation for <ch1_fmt>
	05:13:24 [DEBUG] (tid 139650809255680) ary/core/node.cc(110): Canceling stream <out_0>
	05:13:24 [DEBUG] (tid 139650809255680) ty/cancelable.cc(28): cancelable::do_cancellation
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(362): Canceling ch1_tfrr
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(367): Canceling nodes: consumers
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(372): Canceling ch1_trw
	05:13:24 [DEBUG] (tid 139650809255680) ary/core/node.cc(107): node::do_cancellation for <ch1_trw>
	05:13:24 [DEBUG] (tid 139650809255680) /core/diptera.cc(377): Canceling nodes: bystanders
	05:13:24 [DEBUG] (tid 139650809255680) ource/relayer.cc(67): Canceling relayer
	05:13:24 [ INFO] (tid 139650115036928) l/daq_control.cc(409): Run has stopped
	05:13:24 [ INFO] (tid 139650685581056) oach_receiver.cc(138): TF ROACH receiver is exiting
	05:13:24 [DEBUG] (tid 139650809255680) ource/service.cc(173): Service canceled
	05:13:24 [DEBUG] (tid 139650685581056) oach_receiver.cc(141): Stopping output streams
	05:13:24 [ INFO] (tid 139650809255680) uest_receiver.cc(131): No longer waiting for messages
	05:13:24 [ WARN] (tid 139650115036928) ource/relayer.cc(94): Relayer has been canceled; request not sent
	05:13:24 [ INFO] (tid 139650809255680) ource/service.cc(182): Stopping service on <channel_b_psyllid>
	05:13:24 [DEBUG] (tid 139650809255680) ource/service.cc(291): Stopping consuming messages (consumer amq.ctag-nOWgYf-yPD-_hj_TNMJGSQ)
	05:13:24 [ INFO] (tid 139650115036928) l/daq_control.cc(413): Run was cancelled
	05:13:24 [DEBUG] (tid 139650115036928) l/daq_control.cc(415): Finishing egg files
	05:13:24 [DEBUG] (tid 139650115036928) ty/cancelable.cc(28): cancelable::do_cancellation
	05:13:24 [ INFO] (tid 139650106644224) monarch3_wrap.cc(101): Monarch-on-deck manager is stopping
	05:13:24 [DEBUG] (tid 139650809255680) ource/service.cc(327): Deleting queue <channel_b_psyllid>
	05:13:24 [DEBUG] (tid 139650809255680) uest_receiver.cc(136): Request receiver is done
	05:13:24 [DEBUG] (tid 139650702366464) _mask_trigger.cc(533): FMT has exited the apply-threshold while loop; possible reasons: is_canceled() = 1; f_break_exe_func.load() = 0
	05:13:24 [DEBUG] (tid 139650677188352) ggered_writer.cc(401): Finishing stream <0>
	05:13:24 [DEBUG] (tid 139650710759168) event_builder.cc(526): Stopping output stream
	05:13:24 [ INFO] (tid 139650702366464) _mask_trigger.cc(541): FMT is exiting
	05:13:24 [DEBUG] (tid 139650702366464) _mask_trigger.cc(544): Stopping output stream
	05:13:24 [DEBUG] (tid 139650677188352) monarch3_wrap.cc(492): Finishing stream <0>
	05:13:24 [ INFO] (tid 139650702366464) _mask_trigger.cc(179): FMT has exited
	05:13:24 [ INFO] (tid 139650817648384) /core/diptera.cc(259): threads finished
	05:13:24 [ INFO] (tid 139650817648384) l/daq_control.cc(149): DAQ control is shutting down after midge exited
	05:13:24 [DEBUG] (tid 139650817648384) l/daq_control.cc(157): Midge has finished running
	05:13:24 [DEBUG] (tid 139650904758080) ol/run_server.cc(165): DAQ control thread has ended
	05:13:24 [DEBUG] (tid 139650904758080) ol/run_server.cc(168): Receiver thread has ended
	05:13:24 [DEBUG] (tid 139650904758080) ol/run_server.cc(173): Message relay thread has ended
	05:13:24 [ PROG] (tid 139650904758080) ol/run_server.cc(177): Threads stopped
	05:13:24 [ INFO] (tid 139650123429632) monarch3_wrap.cc(443): Monarch's execute-switch-loop for file </home/cclaessens/psyllid_test_data/trigger_test.egg> is stopping
	05:13:24 [ INFO] (tid 139650115036928) ch3/M3Monarch.cc(252): Finishing writing </home/cclaessens/psyllid_test_data/trigger_test_1.egg>
	05:13:24 [DEBUG] (tid 139650115036928) rch3/M3Stream.cc(672): Finalizing stream with 0 acquisitions and 0 records
	05:13:24 [DEBUG] (tid 139650115036928) monarch3_wrap.cc(196): On-deck file was written out to </home/cclaessens/psyllid_test_data/trigger_test_1.egg>; now removing the file
	05:13:24 [ INFO] (tid 139650115036928) monarch3_wrap.cc(533): Finished writing file </home/cclaessens/psyllid_test_data/trigger_test.egg>
	05:13:24 [DEBUG] (tid 139650115036928) monarch3_wrap.cc(604): Setting monarch stage to <3>
	05:13:24 [ INFO] (tid 139650115036928) ch3/M3Monarch.cc(252): Finishing writing </home/cclaessens/psyllid_test_data/trigger_test.egg>
	05:13:24 [DEBUG] (tid 139650115036928) rch3/M3Stream.cc(672): Finalizing stream with 0 acquisitions and 0 records
	05:13:24 [DEBUG] (tid 139650904758080) tream_manager.cc(425): Clearing node bindings
	05:13:24 [ INFO] (tid 139650904758080) _receiver_fpa.cc(402): Turning off the FPA
	05:13:24 [DEBUG] (tid 139650904758080) _receiver_fpa.cc(412): Unmapping mmap ring
	05:13:24 [DEBUG] (tid 139650904758080) _receiver_fpa.cc(418): freeing f_rd
	05:13:24 [DEBUG] (tid 139650904758080) monarch3_wrap.cc(604): Setting monarch stage to <3>
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class packet-receiver-fpa from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class packet-receiver-fpa from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class triggered-writer from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class triggered-writer from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class tf-roach-receiver from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class tf-roach-receiver from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class roach-freq-monitor from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class roach-freq-monitor from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class roach-time-monitor from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class roach-time-monitor from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-trig-flag from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-trig-flag from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-freq-data from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-freq-data from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-time-data from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class term-time-data from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class streaming-writer from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class streaming-writer from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class events-1ch-fpa from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class events-1ch from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class fmask-1ch-fpa from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class fmask-1ch from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class str-1ch-fpa from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class str-1ch from 0x19926e0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class packet-receiver-socket from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class packet-receiver-socket from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class frequency-mask-trigger from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class frequency-mask-trigger from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class event-builder from 0x1991e90
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class event-builder from 0x1991b00
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class yaml from 0x198e830
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class yaml from 0x198e4a0
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class json from 0x198e830
	05:13:24 [DEBUG] (tid 139650904758080) ility/factory.hh(222): Removing factory for class json from 0x198e4a0
