### ISSUE TITLE
Psyllid stops after deactivate-reactivate sequence

### ISSUE THREAD

**Issue by nsoblath** [project8/psyllid#6]
Reported by Christine on Slack on 7/20/16:

> [W]hen I tell it to stop a run dragonfly sends a stop run requests followed by deactivate and activate which leads to psyllid stopping entirely. If stopping the run is enough I could just remove the two other commands.

**Comment by nsoblath** [comment]
This is fixed as of commit cfb9fb9

**Comment by cclaessens** [comment]
in principle confirmed on zeppelin but see new issue.
