### ISSUE TITLE
psyllid should be able to run without an authentications file

### ISSUE THREAD

**Issue by laroque** [project8/psyllid#68]
In particular, if you're running a batch job with `make-connection: False`, the connection parameters from the file aren't ever used. It would be nice to not need to have the file at all.

**Comment by nsoblath** [comment]
There are two ways to handle this:

1. Remove `.project8_authentications.json` as the default in `server_config.cc`.  It should probably then be added into all of the example config files in the `examples` directory for user convenience.
1. Make a modfication in dripline-cpp's `core.cc`, which checks for `f_make_connection` in the `if` statement at line 56.
