### ISSUE TITLE
Decouple skip-tolerance and n-triggers in event-builder

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#82]
or at least write out the entire skip-buffer

**Comment by laroque** [comment]
was this solved by 87? or do we have more to do? if the latter, could we clarify?

**Comment by cclaessens** [comment]
I think we can close this. I am not planning to make more changes to it and since the last release the skip tolerance buffer is written when it's shorter than the pre-trigger time, which makes things more flexible.
