### ISSUE TITLE
support getting nodes from the active config

### ISSUE THREAD

**Issue by laroque** [project8/psyllid#83]
@nsoblath hopefully you can comment. I think/hope this is quick enough that I could get it in for @wcpettus relatively soon.

It would be useful in dragonfly if it were possible to not only get `[queue].active-config.[stream].[node]`, but to query the active-config for a list of streams and a stream for the list of nodes.

### Use cases
The use case is that the psyllid_interface supports interactions with psyllid in either a streaming or triggered configuration, but needs to specialize what it does based on that knowledge. In order to remain more stateless, we'd like for that interaction to look like:
1) ask psyllid for the list of nodes
2a) if there is a trigger node, proceed to get trigger config
2b) if there is no trigger node, proceed to get streaming config
As opposed to the current model:
1) assume the config is the same as last time and `try` to get that config
2) if psyllid returns an error code, catch the exception and try the other case; cache the new state so that we guess correctly the next time

We could also consider adding the psyllid configuration to the psyllid_interface config file, but then it would be required that that service be changed and restarted whenever we want to change the psyllid configuration itself.

Another use case is that if we could query for a list of nodes, we could then iterate over that list to grab and dump their configurations. This would let us ensure that we're always saving the full active node configuration in the future, when the set of nodes may change.

### Solution?
I think we could loop over the `active_node_bindings` map object and grab the set of keys, building a list of the keys (in a param_array?) and return set of names. Maybe I'm just tired but I'm not immediately remembering where the new RKS binding would need to go. Also, maybe there's some subtle reason why this isn't actually a good idea?

Stretch questions:
- Should we also support getting the list of streams?
- Should we also support getting the entire set of active configurations directly?

**Comment by laroque** [comment]
A specific question for @nsoblath:

What do you think of the following two items. I think 2 is better (and will probably proceed with that unless I hear otherwise).

Option one is to extend the valid response for OP_GET of `<queue>.active-config`, such that `handle_dump_config_request` responds with a list of streams, or a list of nodes if you add a stream to the above RKS. This is easy, it goes in `daq_control.cc` starting at line 729. I don't really like it because returning a list doesn't seem like what you're asking for when you get the active-config.

Option two is to add `handle_dump_stream_list` which takes no extra RKS, and `handle_dump_channel_list` which requires a stream be specified. These are new methods in daq_control and two new registered get handlers in run_server (around line 139)

**Comment by nsoblath** [comment]
@laroque, I agree that your option two is better, but with one modification: those methods should go in stream_manager instead of daq_control.  The information you want to get lives there in `f_streams`.  Be sure to lock `f_manager_mutex` while you access `f_streams`.
