### ISSUE TITLE
Psyllid cannot start a run

### ISSUE THREAD

**Issue by cclaessens** [project8/psyllid#9]
09:13:41 [ INFO] l/daq_control.cc(214): Starting run
09:13:41 [DEBUG] pp/source/hub.cc(299): Sending reply message to <request_reply5f1a44cb-b47a-407a-aa6c-d694d2c7fe3b>:
Return code: 200
Return message: Unable to start run: Do not have midge resource
{
}

It seems error comes from dipteria.cc line 168.
[psyllid-unable-to-start-run.txt](https://github.com/project8/psyllid/files/521524/psyllid-unable-to-start-run.txt)

**Comment by nsoblath** [comment]
This is fixed as of commit cfb9fb9
